### PR TITLE
Add createAnalyzer, deleteAnalyzer operations

### PR DESCRIPTION
**Pull request by otakart**

### CODE REVIEW

**Comment by gabor-boros** [comment]
Hey @otakart, thank you for your PR! 🎉 Could you please extend the existing tests? Then I could merge the PR and release a new version.

**Comment by otakart** [comment]
> Hey @otakart, thank you for your PR! 🎉 Could you please extend the existing tests? Then I could merge the PR and release a new version.

Hi Gabor, thank you for checking this. Also thanks for arangom in general, it helps us a lot 😃 .
Regarding tests - I'm a newbie in golang however I've added some tests following pattern of other tests. Hope it is ok.

**Review by gabor-boros — APPROVED** [review]
Thank you for the tests @otakart! It's great to hear it brings value for you ☺️

I'll merge this right now and will release it later today (after I fixed the CI issues). 

Again, thank you for your PR! 🥳

**Comment by otakart** [comment]
Thank you @gabor-boros !

**Comment by gabor-boros** [comment]
@otakart FYI, the new version (v0.3.0) is released.

**Pull request merged**
